# Generated by Django 5.0.6 on 2025-04-10 03:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Members', '0016_alter_balancepayment_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberdata',
            name='Height',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='memberdata',
            name='Weight',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='memberdata',
            name='Address',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='memberdata',
            name='Date_Of_Birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='memberdata',
            name='Email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='memberdata',
            name='Last_Name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='memberdata',
            name='Registration_Date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='Batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='batch_time', to='Members.batch_db'),
        ),
    ]
