# Generated by Django 5.0.6 on 2025-04-10 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Members', '0017_memberdata_height_memberdata_weight_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memberdata',
            name='Last_Name',
            field=models.CharField(default=' ', max_length=255),
        ),
    ]
